/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.AtividadeDAO;
import Models.Usuario;
import java.awt.Color;
import java.awt.Frame;
import javax.swing.JDialog;

/**
 *
 * @author user
 */
public class Aviso extends JDialog { // extendendo um JDialog para representar um dialogo //

    /**
     * Creates new form Erro
     */
    Usuario usuarioLogado;
    Frame principal;

    public Aviso() {
        setModal(true); // setando como um modal, para não conseguir interagir até que o aviso seja encerrado //
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        panelBorderFundoErro.initMoving(this);
    }

    public Aviso(Frame telaPrincipal, Usuario usuario) {
        setModal(true); // setando como um modal, para não conseguir interagir até que o aviso seja encerrado //
        initComponents();
        setBackground(new Color(0, 0, 0, 0));
        panelBorderFundoErro.initMoving(this);
        usuarioLogado = usuario;
        principal = telaPrincipal;
        MensagemExclusao("Digite o ID");
    }

    public void MensagemErro(String erro) {
        jlTituloFalha.setText("Falha");
        jtfTextoAviso.setText(erro);
        jpBorder.setBackground(Color.decode("#FF3333"));
        this.setVisible(true);
        this.setAlwaysOnTop(true);

    }

    public void MensagemSucesso(String sucesso) {
        jlTituloFalha.setText("Sucesso");
        jtfTextoAviso.setText(sucesso);
        jpBorder.setBackground(Color.decode("#15d283"));
        buttonPersonalizadoSair.setColor(Color.decode("#15d283"));
        buttonPersonalizadoSair.setColorOver(Color.GREEN);
        buttonPersonalizadoSair.setColorClick(Color.GREEN);
        buttonPersonalizadoSair.setText("Ok");
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    public void MensagemExclusao(String acao) {
        jlTituloFalha.setText(acao);
        jtfTextoAviso.setEnabled(true);
        jtfTextoAviso.setEditable(true);
        jtfTextoAviso.setBackground(Color.LIGHT_GRAY);
        jpBorder.setBackground(Color.DARK_GRAY);
        buttonPersonalizadoSair.setColor(Color.decode("#15d283"));
        buttonPersonalizadoSair.setColorOver(Color.GREEN);
        buttonPersonalizadoSair.setColorClick(Color.GREEN);
        buttonPersonalizadoSair.setText("Confirmar");
        this.setVisible(true);
        this.setAlwaysOnTop(true);
    }

    private void processamentoExclusao(Integer id) {
        try {
            // Passa o ID para o DAO para excluir a atividade
            AtividadeDAO atividadeDAO = new AtividadeDAO();
            atividadeDAO.excluirAtividade(usuarioLogado.getCodigo(), id);
        } catch (NumberFormatException e) {
            MensagemErro("O ID inserido não é um número válido!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorderFundoErro = new Components.PanelBorder();
        buttonPersonalizadoSair = new Components.ButtonPersonalizado();
        jpBorder = new javax.swing.JPanel();
        jpFundoTituloFalha = new javax.swing.JPanel();
        jlTituloFalha = new javax.swing.JLabel();
        jtfTextoAviso = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setUndecorated(true);

        panelBorderFundoErro.setBackground(new java.awt.Color(255, 255, 255));
        panelBorderFundoErro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        buttonPersonalizadoSair.setForeground(new java.awt.Color(255, 255, 255));
        buttonPersonalizadoSair.setText("Sair");
        buttonPersonalizadoSair.setBorderColor(new java.awt.Color(250, 250, 250));
        buttonPersonalizadoSair.setBorderPainted(false);
        buttonPersonalizadoSair.setColor(new java.awt.Color(255, 51, 51));
        buttonPersonalizadoSair.setColorClick(new java.awt.Color(204, 0, 0));
        buttonPersonalizadoSair.setColorOver(new java.awt.Color(255, 102, 102));
        buttonPersonalizadoSair.setRadius(15);
        buttonPersonalizadoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizadoSairActionPerformed(evt);
            }
        });

        jpBorder.setBackground(new java.awt.Color(102, 102, 102));

        jpFundoTituloFalha.setBackground(new java.awt.Color(0, 0, 0));

        jlTituloFalha.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jlTituloFalha.setForeground(new java.awt.Color(255, 255, 255));
        jlTituloFalha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTituloFalha.setText("Falha");

        javax.swing.GroupLayout jpFundoTituloFalhaLayout = new javax.swing.GroupLayout(jpFundoTituloFalha);
        jpFundoTituloFalha.setLayout(jpFundoTituloFalhaLayout);
        jpFundoTituloFalhaLayout.setHorizontalGroup(
            jpFundoTituloFalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoTituloFalhaLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(jlTituloFalha, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpFundoTituloFalhaLayout.setVerticalGroup(
            jpFundoTituloFalhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpFundoTituloFalhaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTituloFalha)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpBorderLayout = new javax.swing.GroupLayout(jpBorder);
        jpBorder.setLayout(jpBorderLayout);
        jpBorderLayout.setHorizontalGroup(
            jpBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpFundoTituloFalha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpBorderLayout.setVerticalGroup(
            jpBorderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBorderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpFundoTituloFalha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtfTextoAviso.setEditable(false);
        jtfTextoAviso.setBackground(new java.awt.Color(255, 255, 255));
        jtfTextoAviso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtfTextoAviso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfTextoAviso.setBorder(javax.swing.BorderFactory.createEmptyBorder(6, 6, 6, 6));
        jtfTextoAviso.setCaretColor(new java.awt.Color(255, 255, 255));
        jtfTextoAviso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtfTextoAviso.setOpaque(true);
        jtfTextoAviso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                focusTextGained(evt);
            }
        });

        javax.swing.GroupLayout panelBorderFundoErroLayout = new javax.swing.GroupLayout(panelBorderFundoErro);
        panelBorderFundoErro.setLayout(panelBorderFundoErroLayout);
        panelBorderFundoErroLayout.setHorizontalGroup(
            panelBorderFundoErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderFundoErroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonPersonalizadoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addComponent(jpBorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorderFundoErroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jtfTextoAviso, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panelBorderFundoErroLayout.setVerticalGroup(
            panelBorderFundoErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderFundoErroLayout.createSequentialGroup()
                .addComponent(jpBorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jtfTextoAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPersonalizadoSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderFundoErro, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderFundoErro, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPersonalizadoSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizadoSairActionPerformed
        // TODO add your handling code here:
        if (jlTituloFalha.getText().equals("Digite o ID")) {
            if (jtfTextoAviso.getText().equals("")) {
                this.dispose();
            }else {
                try {
                    int idExclusao = Integer.parseInt(jtfTextoAviso.getText());
                    if (idExclusao > 0) { // Se o ID for válido, realiza a exclusão
                        processamentoExclusao(idExclusao);
                    }
                } catch (NumberFormatException e) {
                    Aviso avisoNovo = new Aviso();
                    avisoNovo.MensagemErro("O ID inserido não é um número válido!");
                }
            }
        }
        this.dispose();
    }//GEN-LAST:event_buttonPersonalizadoSairActionPerformed

    private void focusTextGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_focusTextGained
        // TODO add your handling code here:
        jtfTextoAviso.setCaretPosition(0);
    }//GEN-LAST:event_focusTextGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aviso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aviso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ButtonPersonalizado buttonPersonalizadoSair;
    private javax.swing.JLabel jlTituloFalha;
    private javax.swing.JPanel jpBorder;
    private javax.swing.JPanel jpFundoTituloFalha;
    private javax.swing.JTextField jtfTextoAviso;
    private Components.PanelBorder panelBorderFundoErro;
    // End of variables declaration//GEN-END:variables
}
