/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.AtividadeDAO;
import Models.Atividade;
import Models.StatusType;
import Models.Usuario;
import java.awt.Color;
import static java.lang.Double.isNaN;
import java.time.LocalDate;
import javax.swing.ImageIcon;

/**
 *
 * @author miguel_a_andrade
 */
public class CadastrarAtividade extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAtividade
     */
    // Instância da classe Aviso para exibir mensagens ao usuário
    Aviso aviso = new Aviso();

    // Objeto para interagir com o banco de dados de atividades
    AtividadeDAO atividadeDAO = new AtividadeDAO();

    // Armazena o usuário atualmente logado no sistema
    Usuario usuarioLogado;

    // Construtor que recebe o usuário logado e inicializa a tela
    public CadastrarAtividade(Usuario usuario) {
        usuarioLogado = usuario; // Armazena o usuário logado
        initComponents(); // Inicializa os componentes da interface gráfica
        setBackground(new Color(0, 0, 0, 0)); // Define fundo transparente (necessário para bordas arredondadas)
        PanelBorderWithRadius.initMoving(this); // Habilita movimentação da janela arrastando-a
        jtaObjetivo.setLineWrap(true); // Ativa quebra automática de linha no campo de texto
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBorderWithRadius = new Components.PanelBorder();
        panelBorderTitulo = new Components.PanelBorder();
        jpBordaReta = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtfNomeAtiv = new javax.swing.JTextField();
        jlObjetivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObjetivo = new javax.swing.JTextArea();
        jlDificuldade = new javax.swing.JLabel();
        jcbDificuldade = new javax.swing.JComboBox<>();
        jlStatus = new javax.swing.JLabel();
        jlPrazo = new javax.swing.JLabel();
        jtfPrazo = new javax.swing.JTextField();
        buttonPersonalizadoCriar = new Components.ButtonPersonalizado();
        jcbStatus = new javax.swing.JComboBox<>();
        jbtBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelBorderWithRadius.setBackground(new java.awt.Color(250, 250, 250));

        panelBorderTitulo.setBackground(new java.awt.Color(0, 0, 0));

        jpBordaReta.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpBordaRetaLayout = new javax.swing.GroupLayout(jpBordaReta);
        jpBordaReta.setLayout(jpBordaRetaLayout);
        jpBordaRetaLayout.setHorizontalGroup(
            jpBordaRetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpBordaRetaLayout.setVerticalGroup(
            jpBordaRetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Criação de Atividade ");

        javax.swing.GroupLayout panelBorderTituloLayout = new javax.swing.GroupLayout(panelBorderTitulo);
        panelBorderTitulo.setLayout(panelBorderTituloLayout);
        panelBorderTituloLayout.setHorizontalGroup(
            panelBorderTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBordaReta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorderTituloLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBorderTituloLayout.setVerticalGroup(
            panelBorderTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderTituloLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpBordaReta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlNome.setText("Nome da atividade:");

        jtfNomeAtiv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNomeAtiv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtfNomeAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeAtivActionPerformed(evt);
            }
        });

        jlObjetivo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlObjetivo.setText("Objetivo da atividade:");

        jtaObjetivo.setColumns(20);
        jtaObjetivo.setRows(5);
        jtaObjetivo.setBorder(null);
        jScrollPane1.setViewportView(jtaObjetivo);

        jlDificuldade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlDificuldade.setText("Dificuldade:");

        jcbDificuldade.setBackground(Color.WHITE);
        jcbDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Médio", "Difícil" }));
        jcbDificuldade.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jcbDificuldade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlStatus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlStatus.setText("Status");

        jlPrazo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlPrazo.setText("Prazo em dias");

        jtfPrazo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPrazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtfPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrazoActionPerformed(evt);
            }
        });

        buttonPersonalizadoCriar.setBackground(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoCriar.setForeground(new java.awt.Color(255, 255, 255));
        buttonPersonalizadoCriar.setText("Criar Atividade");
        buttonPersonalizadoCriar.setColor(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoCriar.setColorClick(new java.awt.Color(204, 255, 204));
        buttonPersonalizadoCriar.setColorOver(new java.awt.Color(51, 255, 51));
        buttonPersonalizadoCriar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonPersonalizadoCriar.setRadius(15);
        buttonPersonalizadoCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizadoCriarActionPerformed(evt);
            }
        });

        jcbStatus.setBackground(Color.WHITE);
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Fazendo", "Concluido" }));
        jcbStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jcbStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbStatusItemStateChanged(evt);
            }
        });
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jbtBack.setBackground(new java.awt.Color(250, 250, 250));
        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Back.png"))); // NOI18N
        jbtBack.setBorder(null);
        jbtBack.setContentAreaFilled(false);
        jbtBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackExited(evt);
            }
        });
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBorderWithRadiusLayout = new javax.swing.GroupLayout(PanelBorderWithRadius);
        PanelBorderWithRadius.setLayout(PanelBorderWithRadiusLayout);
        PanelBorderWithRadiusLayout.setHorizontalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtfNomeAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                            .addComponent(jlDificuldade)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jcbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(103, 103, 103)
                                            .addComponent(jlStatus)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jcbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(112, 112, 112))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jlNome)
                                .addGap(281, 281, 281))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jlObjetivo)
                                .addGap(266, 266, 266))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jtfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(324, 324, 324))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(buttonPersonalizadoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(273, 273, 273))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jlPrazo)
                                .addGap(310, 310, 310))))
                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addComponent(jbtBack)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PanelBorderWithRadiusLayout.setVerticalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                .addComponent(panelBorderTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtBack)
                .addGap(8, 8, 8)
                .addComponent(jlNome)
                .addGap(18, 18, 18)
                .addComponent(jtfNomeAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlObjetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDificuldade)
                    .addComponent(jcbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(buttonPersonalizadoCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeAtivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeAtivActionPerformed

    private void jtfPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrazoActionPerformed

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void jbtBackmouseBackEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackEntered
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/BackHover.png")));
    }//GEN-LAST:event_jbtBackmouseBackEntered

    private void jbtBackmouseBackExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackExited
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/Back.png")));
    }//GEN-LAST:event_jbtBackmouseBackExited

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        // Fecha a tela atual e abre a tela principal passando o usuário logado.
        Principal telaPrincipal = new Principal(usuarioLogado);
        this.dispose(); // Fecha a janela atual.
        telaPrincipal.setVisible(true); // Exibe a tela principal.
    }//GEN-LAST:event_jbtBackActionPerformed

    private void buttonPersonalizadoCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizadoCriarActionPerformed
        // TODO add your handling code here:
        // Verifica se os campos estão preenchidos e processa a criação de uma nova atividade.
        if (!jtfNomeAtiv.getText().isEmpty() && jtfNomeAtiv.getText() != null) { // Verifica o nome da atividade.
            if (!jtaObjetivo.getText().isEmpty() && jtaObjetivo.getText() != null) { // Verifica o objetivo.
                try {
                    int prazo = Integer.parseInt(jtfPrazo.getText()); // Converte o prazo para número inteiro.
                    Object selecionadoAtualStatus = jcbStatus.getSelectedItem();
                    String stringStatus = (String) selecionadoAtualStatus;
                    if (prazo > 0 || stringStatus.equals("Concluido")) { // Valida o prazo ou o status como 'Concluido'.
                        Object selecionadoAtualDificuldade = jcbDificuldade.getSelectedItem();
                        String stringDificuldade = (String) selecionadoAtualDificuldade;
                        StatusType status = StatusType.valueOf(stringStatus); // Converte o status para o enum correspondente.

                        // Cria uma nova atividade, adicionando a data de finalização se concluída.
                        if (stringStatus.equals("Concluido")) {
                            LocalDate dataFinalizacao = LocalDate.now();
                            Atividade atividade = new Atividade(usuarioLogado.getCodigo(), prazo, jtfNomeAtiv.getText(), jtaObjetivo.getText(), stringDificuldade, status, dataFinalizacao);
                            atividadeDAO.cadastrarAtividade(atividade);
                        } else {
                            Atividade atividade = new Atividade(usuarioLogado.getCodigo(), prazo, jtfNomeAtiv.getText(), jtaObjetivo.getText(), stringDificuldade, status);
                            atividadeDAO.cadastrarAtividade(atividade);
                        }

                        // Limpa os campos e volta para a tela principal.
                        jtfNomeAtiv.setText("");
                        jtaObjetivo.setText("");
                        jtfPrazo.setText("");
                        jcbDificuldade.setSelectedIndex(0);
                        jcbStatus.setSelectedIndex(0);
                        Principal principal = new Principal(usuarioLogado);
                        this.dispose();
                        principal.setVisible(true);
                    } else {
                        aviso.MensagemErro("Prazo é menor ou igual a 0!");
                    }
                } catch (NumberFormatException e) {
                    // Exibe mensagem de erro se o prazo não for um número válido.
                    aviso.MensagemErro("O valor do prazo não é um número válido!");
                }
            } else {
                aviso.MensagemErro("Objetivo está vazio!");
            }
        } else {
            aviso.MensagemErro("Nome da Atividade está vazio!");
        }
    }//GEN-LAST:event_buttonPersonalizadoCriarActionPerformed

    private void jcbStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbStatusItemStateChanged
        // TODO add your handling code here:
        // Verifica a mudança de status no combobox 'jcbStatus'.
        // Se o status for 'Concluido', define o prazo como 0 e desabilita o campo
        Object selecionadoAtualStatus = jcbStatus.getSelectedItem();
        String stringStatus = (String) selecionadoAtualStatus;
        if (stringStatus.equals("Concluido")) {
            jtfPrazo.setText("0");
            jtfPrazo.setEnabled(false);
        } else {
            jtfPrazo.setText("");
            jtfPrazo.setEnabled(true);
        }
    }//GEN-LAST:event_jcbStatusItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.PanelBorder PanelBorderWithRadius;
    private Components.ButtonPersonalizado buttonPersonalizadoCriar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtBack;
    private javax.swing.JComboBox<String> jcbDificuldade;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JLabel jlDificuldade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlObjetivo;
    private javax.swing.JLabel jlPrazo;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpBordaReta;
    private javax.swing.JTextArea jtaObjetivo;
    private javax.swing.JTextField jtfNomeAtiv;
    private javax.swing.JTextField jtfPrazo;
    private Components.PanelBorder panelBorderTitulo;
    // End of variables declaration//GEN-END:variables
}
