/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.AtividadeDAO;
import Models.Atividade;
import Models.StatusType;
import Models.Usuario;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.ImageIcon;

/**
 *
 * @author miguel_a_andrade
 */

public class EditarAtividade extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarAtividade
     */
    Aviso aviso = new Aviso();
    AtividadeDAO atividadeDAO = new AtividadeDAO();
    Usuario usuarioLogado;
    Atividade atividade;
    public EditarAtividade(Usuario usuario, Integer id) {
        usuarioLogado = usuario;
        initComponents();
        setBackground(new Color(0, 0, 0, 0)); // Atribuindo o fundo para ser transparente ( para aparecer a borda arredondada )
        PanelBorderWithRadius.initMoving(this); // Atribuindo o frame no metodo para o a movimentação da tela
        jtaObjetivo.setLineWrap(true);
        jtaAndamento.setLineWrap(true);
        atividade = atividadeDAO.atividadePorID(usuarioLogado.getCodigo(), id);
        atribuirValores(atividade);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBorderWithRadius = new Components.PanelBorder();
        panelBorderTitulo = new Components.PanelBorder();
        jpBordaReta = new javax.swing.JPanel();
        jlTitulo = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jtfNomeAtiv = new javax.swing.JTextField();
        jlObjetivo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaObjetivo = new javax.swing.JTextArea();
        jlDificuldade = new javax.swing.JLabel();
        jcbDificuldade = new javax.swing.JComboBox<>();
        jlStatus = new javax.swing.JLabel();
        jlPrazo = new javax.swing.JLabel();
        jtfPrazo = new javax.swing.JTextField();
        buttonPersonalizadoEditar = new Components.ButtonPersonalizado();
        jcbStatus = new javax.swing.JComboBox<>();
        jbtBack = new javax.swing.JButton();
        jlAndamento = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaAndamento = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelBorderWithRadius.setBackground(new java.awt.Color(250, 250, 250));

        panelBorderTitulo.setBackground(new java.awt.Color(0, 0, 0));

        jpBordaReta.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jpBordaRetaLayout = new javax.swing.GroupLayout(jpBordaReta);
        jpBordaReta.setLayout(jpBordaRetaLayout);
        jpBordaRetaLayout.setHorizontalGroup(
            jpBordaRetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpBordaRetaLayout.setVerticalGroup(
            jpBordaRetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        jlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("Detalhes da Atividade ");

        javax.swing.GroupLayout panelBorderTituloLayout = new javax.swing.GroupLayout(panelBorderTitulo);
        panelBorderTitulo.setLayout(panelBorderTituloLayout);
        panelBorderTituloLayout.setHorizontalGroup(
            panelBorderTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpBordaReta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelBorderTituloLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBorderTituloLayout.setVerticalGroup(
            panelBorderTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBorderTituloLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpBordaReta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jlNome.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlNome.setText("Nome da atividade:");

        jtfNomeAtiv.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfNomeAtiv.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtfNomeAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeAtivActionPerformed(evt);
            }
        });

        jlObjetivo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlObjetivo.setText("Objetivo da atividade:");

        jtaObjetivo.setColumns(20);
        jtaObjetivo.setRows(5);
        jtaObjetivo.setBorder(null);
        jScrollPane1.setViewportView(jtaObjetivo);

        jlDificuldade.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlDificuldade.setText("Dificuldade:");

        jcbDificuldade.setBackground(Color.WHITE);
        jcbDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Médio", "Difícil" }));
        jcbDificuldade.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jcbDificuldade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jlStatus.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlStatus.setText("Status");

        jlPrazo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlPrazo.setText("Prazo em dias");

        jtfPrazo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtfPrazo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtfPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfPrazoActionPerformed(evt);
            }
        });

        buttonPersonalizadoEditar.setBackground(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoEditar.setForeground(new java.awt.Color(255, 255, 255));
        buttonPersonalizadoEditar.setText("Editar Atividade");
        buttonPersonalizadoEditar.setColor(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoEditar.setColorClick(new java.awt.Color(204, 255, 204));
        buttonPersonalizadoEditar.setColorOver(new java.awt.Color(51, 255, 51));
        buttonPersonalizadoEditar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        buttonPersonalizadoEditar.setRadius(15);
        buttonPersonalizadoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizadoEditarActionPerformed(evt);
            }
        });

        jcbStatus.setBackground(Color.WHITE);
        jcbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendente", "Fazendo", "Concluido" }));
        jcbStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1)));
        jcbStatus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jcbStatus.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbStatusItemStateChanged(evt);
            }
        });
        jcbStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbStatusActionPerformed(evt);
            }
        });

        jbtBack.setBackground(new java.awt.Color(250, 250, 250));
        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Back.png"))); // NOI18N
        jbtBack.setBorder(null);
        jbtBack.setContentAreaFilled(false);
        jbtBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackExited(evt);
            }
        });
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        jlAndamento.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlAndamento.setText("Ultimo andamento da atividade:");

        jtaAndamento.setColumns(20);
        jtaAndamento.setRows(5);
        jtaAndamento.setBorder(null);
        jScrollPane2.setViewportView(jtaAndamento);

        javax.swing.GroupLayout PanelBorderWithRadiusLayout = new javax.swing.GroupLayout(PanelBorderWithRadius);
        PanelBorderWithRadius.setLayout(PanelBorderWithRadiusLayout);
        PanelBorderWithRadiusLayout.setHorizontalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jtfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addComponent(jlPrazo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(309, 309, 309))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addComponent(jbtBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                                .addGap(163, 163, 163)
                                                .addComponent(jlObjetivo))
                                            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                                .addComponent(jlDificuldade)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jcbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(103, 103, 103)
                                                .addComponent(jlStatus)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                                            .addComponent(jlNome)
                                            .addGap(169, 169, 169)))
                                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(buttonPersonalizadoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtfNomeAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(112, 112, 112))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlAndamento)
                .addGap(214, 214, 214))
        );
        PanelBorderWithRadiusLayout.setVerticalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                .addComponent(panelBorderTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBack))
                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jlNome)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfNomeAtiv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlObjetivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlAndamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlDificuldade)
                    .addComponent(jcbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStatus)
                    .addComponent(jcbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(buttonPersonalizadoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtfNomeAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeAtivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeAtivActionPerformed

    private void jtfPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfPrazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfPrazoActionPerformed

    private void jcbStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbStatusActionPerformed

    private void jbtBackmouseBackEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackEntered
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/BackHover.png")));
    }//GEN-LAST:event_jbtBackmouseBackEntered

    private void jbtBackmouseBackExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackExited
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/Back.png")));
    }//GEN-LAST:event_jbtBackmouseBackExited

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        Principal telaPrincipal = new Principal(usuarioLogado);
        this.dispose();
        telaPrincipal.setVisible(true);
    }//GEN-LAST:event_jbtBackActionPerformed

    private void atribuirValores(Atividade atividade) {
        // Obtém a atividade pelo ID
        if (atividade != null) {
            // Atribui os valores aos campos do formulário
            jtfNomeAtiv.setText(atividade.getNome());
            jtaObjetivo.setText(atividade.getObj());

            // Verifica se o campo andamento não é nulo antes de setar
            jtaAndamento.setText(atividade.getAndamento() != null ? atividade.getAndamento() : "");

            jtfPrazo.setText(String.valueOf((atividade.getPrazo() > 0 ? atividade.getPrazo() : "0")));

            // Ajusta os valores do JComboBox para status e dificuldade
            jcbStatus.setSelectedItem(atividade.getStatus().toString());
            jcbDificuldade.setSelectedItem(atividade.getDificuldade());
        } else {
            aviso.MensagemErro("Não foi possível carregar os valores da atividade com ID: " + atividade.getCodigo());
        }
    }

    private void buttonPersonalizadoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizadoEditarActionPerformed
        // TODO add your handling code here:
        try {
            if (jtfNomeAtiv.getText() == null || jtfNomeAtiv.getText().isEmpty()) {
                aviso.MensagemErro("Nome da Atividade não pode estar vazio.");
                return;
            }
            if (jtaObjetivo.getText() == null || jtaObjetivo.getText().isEmpty()) {
                aviso.MensagemErro("Objetivo não pode estar vazio.");
                return;
            }
            if (jtfPrazo.getText() == null || jtfPrazo.getText().isEmpty() || Integer.parseInt(jtfPrazo.getText()) <= 0) {
                aviso.MensagemErro("Prazo não pode estar vazio e deve ser maior que 0.");
                return;
            }

            // Obtém os valores dos campos
            String nome = jtfNomeAtiv.getText();
            String obj = jtaObjetivo.getText();
            String andamento = jtaAndamento.getText();
            String dificuldade = (String) jcbDificuldade.getSelectedItem();
            String statusString = (String) jcbStatus.getSelectedItem();
            StatusType status = StatusType.valueOf(statusString);
            int prazo = Integer.parseInt(jtfPrazo.getText());

            // Define data de finalização caso o status seja concluído
            LocalDate dataFinalizacao = null;
            if (status == StatusType.Concluido) {
                dataFinalizacao = LocalDate.now();
            }

            atividade.setNome(nome);
            atividade.setObj(obj);
            atividade.setAndamento(andamento);
            atividade.setStatus(status);
            atividade.setDificuldade(dificuldade);
            atividade.setPrazo(prazo);
            atividade.setData_finalizacao(dataFinalizacao);

            atividadeDAO.editarAtividade(atividade);
            
            Principal principal = new Principal(usuarioLogado);
            this.dispose();
            principal.setVisible(true);
        } catch (NumberFormatException e) {
            aviso.MensagemErro("Prazo deve ser um número válido.");
        }catch (Exception e) {
            aviso.MensagemErro("Erro ao editar atividade: " + e.getMessage());
        }
    }//GEN-LAST:event_buttonPersonalizadoEditarActionPerformed

    private void jcbStatusItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbStatusItemStateChanged
        // TODO add your handling code here:

        Object selecionadoAtualStatus = jcbStatus.getSelectedItem();
        String stringStatus = (String) selecionadoAtualStatus;
        if (stringStatus.equals("Concluido")) {
            jtfPrazo.setText("0");
            jtfPrazo.setEnabled(false);
        } else {
            jtfPrazo.setEnabled(true);
        }
    }//GEN-LAST:event_jcbStatusItemStateChanged

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.PanelBorder PanelBorderWithRadius;
    private Components.ButtonPersonalizado buttonPersonalizadoEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbtBack;
    private javax.swing.JComboBox<String> jcbDificuldade;
    private javax.swing.JComboBox<String> jcbStatus;
    private javax.swing.JLabel jlAndamento;
    private javax.swing.JLabel jlDificuldade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlObjetivo;
    private javax.swing.JLabel jlPrazo;
    private javax.swing.JLabel jlStatus;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JPanel jpBordaReta;
    private javax.swing.JTextArea jtaAndamento;
    private javax.swing.JTextArea jtaObjetivo;
    private javax.swing.JTextField jtfNomeAtiv;
    private javax.swing.JTextField jtfPrazo;
    private Components.PanelBorder panelBorderTitulo;
    // End of variables declaration//GEN-END:variables
}
