/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author miguel_a_andrade
 */
public class Principal extends javax.swing.JFrame {
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cardButton1.setTemp1(cardButton1.getGradientStartColor());
        cardButton1.setTemp2(cardButton1.getGradientFinalColor());
        setBackground(new Color(0, 0, 0, 0));
        panelBorderWithRadius.initMoving(this);
        buttonPersonalizado1.setText("<html><center>Atividades não iniciadas<br>0</center></html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBorderWithRadius = new Components.PanelBorder();
        menuPrincipal = new Components.MenuPrincipal();
        jbtExit = new javax.swing.JButton();
        jbtMinimize = new javax.swing.JButton();
        buttonPersonalizado1 = new Components.ButtonPersonalizado();
        buttonPersonalizado2 = new Components.ButtonPersonalizado();
        buttonPersonalizado3 = new Components.ButtonPersonalizado();
        cardButton1 = new Components.CardButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelBorderWithRadius.setBackground(new java.awt.Color(250, 250, 250));

        jbtExit.setBackground(new java.awt.Color(250, 250, 250));
        jbtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/IconClose.png"))); // NOI18N
        jbtExit.setBorder(null);
        jbtExit.setContentAreaFilled(false);
        jbtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtExitmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtExitmouseExited(evt);
            }
        });
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });

        jbtMinimize.setBackground(new java.awt.Color(250, 250, 250));
        jbtMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Minimize.png"))); // NOI18N
        jbtMinimize.setBorder(null);
        jbtMinimize.setContentAreaFilled(false);
        jbtMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtMinimizemouseMinimizeEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtMinimizemouseMinimizeExited(evt);
            }
        });
        jbtMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMinimizeActionPerformed(evt);
            }
        });

        buttonPersonalizado1.setBorder(null);
        buttonPersonalizado1.setForeground(new java.awt.Color(255, 255, 255));
        buttonPersonalizado1.setText("Atividades não iniciadas 5");
        buttonPersonalizado1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonPersonalizado1.setGradient(true);
        buttonPersonalizado1.setGradientFinalColor(new java.awt.Color(243, 115, 53));
        buttonPersonalizado1.setGradientStartColor(new java.awt.Color(253, 200, 48));
        buttonPersonalizado1.setRadius(15);
        buttonPersonalizado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizado1ActionPerformed(evt);
            }
        });

        buttonPersonalizado2.setText("buttonPersonalizado2");
        buttonPersonalizado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizado2ActionPerformed(evt);
            }
        });

        buttonPersonalizado3.setText("buttonPersonalizado3");

        cardButton1.setColor(new java.awt.Color(255, 153, 153));
        cardButton1.setColorClick(new java.awt.Color(255, 102, 0));
        cardButton1.setGradient(true);
        cardButton1.setGradientFinalColor(new java.awt.Color(243, 115, 53));
        cardButton1.setGradientFinalColorHover(new java.awt.Color(231, 103, 0));
        cardButton1.setGradientStartColor(new java.awt.Color(253, 200, 48));
        cardButton1.setGradientStartColorHover(new java.awt.Color(253, 170, 97));

        javax.swing.GroupLayout panelBorderWithRadiusLayout = new javax.swing.GroupLayout(panelBorderWithRadius);
        panelBorderWithRadius.setLayout(panelBorderWithRadiusLayout);
        panelBorderWithRadiusLayout.setHorizontalGroup(
            panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5))
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(buttonPersonalizado1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(buttonPersonalizado2, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(buttonPersonalizado3, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70))
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(cardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelBorderWithRadiusLayout.setVerticalGroup(
            panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
            .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(panelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonPersonalizado2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonPersonalizado3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(buttonPersonalizado1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(59, 59, 59)
                .addComponent(cardButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderWithRadius, javax.swing.GroupLayout.DEFAULT_SIZE, 1278, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBorderWithRadius, 715, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExitmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExitmouseEntered
        // TODO add your handling code here:
        jbtExit.setIcon(new ImageIcon(getClass().getResource("/Icon/IconCloseHover.png")));
    }//GEN-LAST:event_jbtExitmouseEntered

    private void jbtExitmouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExitmouseExited
        // TODO add your handling code here:
        jbtExit.setIcon(new ImageIcon(getClass().getResource("/Icon/IconClose.png")));
    }//GEN-LAST:event_jbtExitmouseExited

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtExitActionPerformed

    private void jbtMinimizemouseMinimizeEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtMinimizemouseMinimizeEntered
        // TODO add your handling code here:
        jbtMinimize.setIcon(new ImageIcon(getClass().getResource("/Icon/MinimizeHover.png")));
    }//GEN-LAST:event_jbtMinimizemouseMinimizeEntered

    private void jbtMinimizemouseMinimizeExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtMinimizemouseMinimizeExited
        // TODO add your handling code here:
        jbtMinimize.setIcon(new ImageIcon(getClass().getResource("/Icon/Minimize.png")));
    }//GEN-LAST:event_jbtMinimizemouseMinimizeExited

    private void jbtMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMinimizeActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jbtMinimizeActionPerformed

    private void buttonPersonalizado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizado2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPersonalizado2ActionPerformed

    private void buttonPersonalizado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonPersonalizado1ActionPerformed

    private void teste(){
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.ButtonPersonalizado buttonPersonalizado1;
    private Components.ButtonPersonalizado buttonPersonalizado2;
    private Components.ButtonPersonalizado buttonPersonalizado3;
    private Components.CardButton cardButton1;
    private javax.swing.JButton jbtExit;
    private javax.swing.JButton jbtMinimize;
    private Components.MenuPrincipal menuPrincipal;
    private Components.PanelBorder panelBorderWithRadius;
    // End of variables declaration//GEN-END:variables
}
