/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.UsuarioDAO;
import Models.Usuario;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class Redefinir extends javax.swing.JFrame {

    UsuarioDAO usuarioDAO = new UsuarioDAO();
    Boolean visibility = false;
    Aviso aviso = new Aviso();

    /**
     * Creates new form Redefinir
     */
    public Redefinir() {
        initComponents();
        setBackground(new Color(0, 0, 0, 0)); // Atribuindo o fundo para ser transparente ( para aparecer a borda arredondada )
        PanelBorderWithRadius.initMoving(this); // Atribuindo o frame no metodo para o a movimentação da tela
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelBorderWithRadius = new Components.PanelBorder();
        menuPadraoRedefinir = new Components.MenuPadrao();
        jbtExit = new javax.swing.JButton();
        jbtMinimize = new javax.swing.JButton();
        jbtBack = new javax.swing.JButton();
        jlEmail = new javax.swing.JLabel();
        jlSenha = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jpfSenha = new javax.swing.JPasswordField();
        jlTituloRedefinir = new javax.swing.JLabel();
        buttonPersonalizadoRedefinir = new Components.ButtonPersonalizado();
        jbtVisibility = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelBorderWithRadius.setBackground(new java.awt.Color(250, 250, 250));

        jbtExit.setBackground(new java.awt.Color(250, 250, 250));
        jbtExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/IconClose.png"))); // NOI18N
        jbtExit.setBorder(null);
        jbtExit.setContentAreaFilled(false);
        jbtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtExitmouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtExitmouseExited(evt);
            }
        });
        jbtExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExitActionPerformed(evt);
            }
        });

        jbtMinimize.setBackground(new java.awt.Color(250, 250, 250));
        jbtMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Minimize.png"))); // NOI18N
        jbtMinimize.setBorder(null);
        jbtMinimize.setContentAreaFilled(false);
        jbtMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtMinimizemouseMinimizeEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtMinimizemouseMinimizeExited(evt);
            }
        });
        jbtMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtMinimizeActionPerformed(evt);
            }
        });

        jbtBack.setBackground(new java.awt.Color(250, 250, 250));
        jbtBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Back.png"))); // NOI18N
        jbtBack.setBorder(null);
        jbtBack.setContentAreaFilled(false);
        jbtBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtBackmouseBackExited(evt);
            }
        });
        jbtBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtBackActionPerformed(evt);
            }
        });

        jlEmail.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlEmail.setText("Email:");

        jlSenha.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jlSenha.setText("Senha:");

        jtfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtfEmail.setForeground(new java.awt.Color(51, 51, 51));
        jtfEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jtfEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfEmailActionPerformed(evt);
            }
        });

        jpfSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jpfSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jlTituloRedefinir.setFont(new java.awt.Font("Segoe UI", 1, 35)); // NOI18N
        jlTituloRedefinir.setText("Redefinir senha");

        buttonPersonalizadoRedefinir.setBackground(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoRedefinir.setForeground(new java.awt.Color(255, 255, 255));
        buttonPersonalizadoRedefinir.setText("Redefinir");
        buttonPersonalizadoRedefinir.setBorderPainted(false);
        buttonPersonalizadoRedefinir.setColor(new java.awt.Color(20, 208, 130));
        buttonPersonalizadoRedefinir.setColorClick(new java.awt.Color(204, 255, 204));
        buttonPersonalizadoRedefinir.setColorOver(new java.awt.Color(51, 255, 51));
        buttonPersonalizadoRedefinir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonPersonalizadoRedefinir.setRadius(20);
        buttonPersonalizadoRedefinir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPersonalizadoRedefinirActionPerformed(evt);
            }
        });

        jbtVisibility.setBackground(new java.awt.Color(250, 250, 250));
        jbtVisibility.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/NoVisibility.png"))); // NOI18N
        jbtVisibility.setBorder(null);
        jbtVisibility.setContentAreaFilled(false);
        jbtVisibility.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtVisibility.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtVisibilitymouseVisibilityEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtVisibilitymouseVisibilityExited(evt);
            }
        });
        jbtVisibility.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtVisibilityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBorderWithRadiusLayout = new javax.swing.GroupLayout(PanelBorderWithRadius);
        PanelBorderWithRadius.setLayout(PanelBorderWithRadiusLayout);
        PanelBorderWithRadiusLayout.setHorizontalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                .addComponent(menuPadraoRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlTituloRedefinir)
                            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlSenha)
                                    .addComponent(jlEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtfEmail)
                                    .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(60, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPersonalizadoRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(129, 129, 129))))
        );
        PanelBorderWithRadiusLayout.setVerticalGroup(
            PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBorderWithRadiusLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(menuPadraoRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtBack)
                    .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jbtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(PanelBorderWithRadiusLayout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addComponent(jbtMinimize, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(184, 184, 184)
                .addComponent(jlTituloRedefinir)
                .addGap(35, 35, 35)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmail)
                    .addComponent(jtfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBorderWithRadiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlSenha)
                        .addComponent(jpfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtVisibility, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(buttonPersonalizadoRedefinir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBorderWithRadius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtExitmouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExitmouseEntered
        // TODO add your handling code here:
        jbtExit.setIcon(new ImageIcon(getClass().getResource("/Icon/IconCloseHover.png")));
    }//GEN-LAST:event_jbtExitmouseEntered

    private void jbtExitmouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExitmouseExited
        // TODO add your handling code here:
        jbtExit.setIcon(new ImageIcon(getClass().getResource("/Icon/IconClose.png")));
    }//GEN-LAST:event_jbtExitmouseExited

    private void jbtExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jbtExitActionPerformed

    private void jbtMinimizemouseMinimizeEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtMinimizemouseMinimizeEntered
        // TODO add your handling code here:
        jbtMinimize.setIcon(new ImageIcon(getClass().getResource("/Icon/MinimizeHover.png")));
    }//GEN-LAST:event_jbtMinimizemouseMinimizeEntered

    private void jbtMinimizemouseMinimizeExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtMinimizemouseMinimizeExited
        // TODO add your handling code here:
        jbtMinimize.setIcon(new ImageIcon(getClass().getResource("/Icon/Minimize.png")));
    }//GEN-LAST:event_jbtMinimizemouseMinimizeExited

    private void jbtMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtMinimizeActionPerformed
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jbtMinimizeActionPerformed

    private void jbtBackmouseBackEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackEntered
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/BackHover.png")));
    }//GEN-LAST:event_jbtBackmouseBackEntered

    private void jbtBackmouseBackExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtBackmouseBackExited
        // TODO add your handling code here:
        jbtBack.setIcon(new ImageIcon(getClass().getResource("/Icon/Back.png")));
    }//GEN-LAST:event_jbtBackmouseBackExited

    private void jbtBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBackActionPerformed
        // TODO add your handling code here:
        Login telaLogin = new Login();
        this.dispose();
        telaLogin.setVisible(true);
    }//GEN-LAST:event_jbtBackActionPerformed

    private void jtfEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfEmailActionPerformed

    private void buttonPersonalizadoRedefinirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPersonalizadoRedefinirActionPerformed
        // TODO add your handling code here:
        if (!jtfEmail.getText().isEmpty() && jtfEmail.getText() != null) {
            if (jpfSenha.getPassword().length > 0) {
                String email = jtfEmail.getText().trim();
                String senha = new String(jpfSenha.getPassword());
                usuarioDAO.alterarSenha(email, senha);
            } else {
                aviso.MensagemErro("Senha está vazia!");
            }
        } else {
            aviso.MensagemErro("Email está vazio!");
        }

    }//GEN-LAST:event_buttonPersonalizadoRedefinirActionPerformed

    private void jbtVisibilitymouseVisibilityEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtVisibilitymouseVisibilityEntered
        // TODO add your handling code here:
        if (visibility == true) {
            jbtVisibility.setIcon(new ImageIcon(getClass().getResource("/Icon/VisibilityHover.png")));
        } else {
            jbtVisibility.setIcon(new ImageIcon(getClass().getResource("/Icon/NoVisibilityHover.png")));
        }
    }//GEN-LAST:event_jbtVisibilitymouseVisibilityEntered

    private void jbtVisibilitymouseVisibilityExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtVisibilitymouseVisibilityExited
        if (visibility == true) {
            jbtVisibility.setIcon(new ImageIcon(getClass().getResource("/Icon/Visibility.png")));
        } else {
            jbtVisibility.setIcon(new ImageIcon(getClass().getResource("/Icon/NoVisibility.png")));
        }
    }//GEN-LAST:event_jbtVisibilitymouseVisibilityExited

    private void jbtVisibilityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtVisibilityActionPerformed
        // TODO add your handling code here:
        if (visibility) {
            jpfSenha.setEchoChar('*');
            visibility = false;
        } else {
            jpfSenha.setEchoChar((char) 0);
            visibility = true;
        }
    }//GEN-LAST:event_jbtVisibilityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Redefinir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Redefinir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Redefinir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Redefinir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Redefinir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Components.PanelBorder PanelBorderWithRadius;
    private Components.ButtonPersonalizado buttonPersonalizadoRedefinir;
    private javax.swing.JButton jbtBack;
    private javax.swing.JButton jbtExit;
    private javax.swing.JButton jbtMinimize;
    private javax.swing.JButton jbtVisibility;
    private javax.swing.JLabel jlEmail;
    private javax.swing.JLabel jlSenha;
    private javax.swing.JLabel jlTituloRedefinir;
    private javax.swing.JPasswordField jpfSenha;
    private javax.swing.JTextField jtfEmail;
    private Components.MenuPadrao menuPadraoRedefinir;
    // End of variables declaration//GEN-END:variables
}
