/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import Models.Usuario;
import Telas.Aviso;
import Telas.CadastrarAtividade;
import Telas.Principal;
import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/**
 *
 * @author miguel_a_andrade
 */
public class MenuPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form MenuPrincipal
     */
    Usuario usuarioLogado;
    Principal principal;
    Aviso aviso = new Aviso();
    public MenuPrincipal(Principal principalFrame, Usuario usuario) {
        usuarioLogado = usuario;
        principal = principalFrame;
        initComponents();
        setOpaque(false);
    }

    public MenuPrincipal() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs; // Converto o Graphics em Graphics2D pra gráficos avançados
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // Ativo o suavizamento das bordas para deixar o desenho mais suave
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#000000"), getWidth(), getHeight(), Color.decode("#737373")); // Gradiente que vai do preto no canto superior esquerdo até um cinza no canto inferior direito
        g2.setPaint(g); //  usar esse gradiente para o desenho
        g2.fillRoundRect(0, 0, getWidth() - 20, getHeight(), 15, 15); //  Preencho um retângulo arredondado que ocupa toda a área do componente com um radius de 15
        g2.fillRect(getWidth() - 30, 0, 30, getHeight()); // Retângulo reto no lado direito
        super.paintComponent(grphcs); //  Chamando o método da classe pai para garantir que o componente seja desenhado corretamente
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMy = new javax.swing.JLabel();
        jlActivities = new javax.swing.JLabel();
        jbtCadastrarAtividade = new javax.swing.JButton();
        jbtRedefinirSenha = new javax.swing.JButton();
        jbtExcluirAtividade = new javax.swing.JButton();

        jlMy.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jlMy.setForeground(new java.awt.Color(255, 255, 255));
        jlMy.setText("My");

        jlActivities.setFont(new java.awt.Font("Segoe UI", 1, 45)); // NOI18N
        jlActivities.setForeground(new java.awt.Color(255, 255, 255));
        jlActivities.setText("Activities");

        jbtCadastrarAtividade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtCadastrarAtividade.setForeground(new java.awt.Color(255, 255, 255));
        jbtCadastrarAtividade.setText("Cadastrar Atividade");
        jbtCadastrarAtividade.setBorderPainted(false);
        jbtCadastrarAtividade.setContentAreaFilled(false);
        jbtCadastrarAtividade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtCadastrarAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtCadastrarAtividadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtCadastrarAtividadeMouseExited(evt);
            }
        });
        jbtCadastrarAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCadastrarAtividadeActionPerformed(evt);
            }
        });

        jbtRedefinirSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtRedefinirSenha.setForeground(new java.awt.Color(255, 255, 255));
        jbtRedefinirSenha.setText("Redefinir Senha");
        jbtRedefinirSenha.setBorderPainted(false);
        jbtRedefinirSenha.setContentAreaFilled(false);
        jbtRedefinirSenha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtRedefinirSenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtRedefinirSenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtRedefinirSenhaMouseExited(evt);
            }
        });
        jbtRedefinirSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRedefinirSenhaActionPerformed(evt);
            }
        });

        jbtExcluirAtividade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtExcluirAtividade.setForeground(new java.awt.Color(255, 255, 255));
        jbtExcluirAtividade.setText("Excluir Atividade");
        jbtExcluirAtividade.setBorderPainted(false);
        jbtExcluirAtividade.setContentAreaFilled(false);
        jbtExcluirAtividade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtExcluirAtividade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtExcluirAtividadeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jbtExcluirAtividadeMouseExited(evt);
            }
        });
        jbtExcluirAtividade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtExcluirAtividadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtCadastrarAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlActivities)
                                .addComponent(jlMy))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jbtRedefinirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtExcluirAtividade, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jlMy)
                .addGap(0, 0, 0)
                .addComponent(jlActivities)
                .addGap(33, 33, 33)
                .addComponent(jbtCadastrarAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtExcluirAtividade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 405, Short.MAX_VALUE)
                .addComponent(jbtRedefinirSenha)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbtCadastrarAtividadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCadastrarAtividadeMouseEntered
        // TODO add your handling code here:
        Color corAzulHover = new Color(89, 133, 225);
        jbtCadastrarAtividade.setForeground(corAzulHover);
    }//GEN-LAST:event_jbtCadastrarAtividadeMouseEntered

    private void jbtCadastrarAtividadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtCadastrarAtividadeMouseExited
        // TODO add your handling code here:
        jbtCadastrarAtividade.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbtCadastrarAtividadeMouseExited

    private void jbtRedefinirSenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtRedefinirSenhaMouseEntered
        // TODO add your handling code here:
        Color corAzulHover = new Color(89, 133, 225);
        jbtRedefinirSenha.setForeground(corAzulHover);
    }//GEN-LAST:event_jbtRedefinirSenhaMouseEntered

    private void jbtRedefinirSenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtRedefinirSenhaMouseExited
        // TODO add your handling code here:
        jbtRedefinirSenha.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbtRedefinirSenhaMouseExited

    private void jbtRedefinirSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRedefinirSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtRedefinirSenhaActionPerformed

    private void jbtExcluirAtividadeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExcluirAtividadeMouseEntered
        // TODO add your handling code here:
        Color corAzulHover = new Color(89, 133, 225);
        jbtExcluirAtividade.setForeground(corAzulHover);
    }//GEN-LAST:event_jbtExcluirAtividadeMouseEntered

    private void jbtExcluirAtividadeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbtExcluirAtividadeMouseExited
        // TODO add your handling code here:
        jbtExcluirAtividade.setForeground(Color.WHITE);
    }//GEN-LAST:event_jbtExcluirAtividadeMouseExited

    private void jbtExcluirAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtExcluirAtividadeActionPerformed
        // TODO add your handling code here:
        Aviso aviso = new Aviso(principal, usuarioLogado);
        principal.atualizarLista();
    }//GEN-LAST:event_jbtExcluirAtividadeActionPerformed

    private void jbtCadastrarAtividadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCadastrarAtividadeActionPerformed
        // TODO add your handling code here:
        CadastrarAtividade telaCadastroAtividade = new CadastrarAtividade(usuarioLogado);
        telaCadastroAtividade.setVisible(true);
        principal.dispose();
    }//GEN-LAST:event_jbtCadastrarAtividadeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtCadastrarAtividade;
    private javax.swing.JButton jbtExcluirAtividade;
    private javax.swing.JButton jbtRedefinirSenha;
    private javax.swing.JLabel jlActivities;
    private javax.swing.JLabel jlMy;
    // End of variables declaration//GEN-END:variables
}
