/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Components;

import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import javax.swing.JFrame;

/**
 *
 * @author user
 */
public class MenuPadrao extends javax.swing.JPanel {

    /**
     * Creates new form MenuPadrao
     */
    public MenuPadrao() {
        initComponents();
        setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    @Override
    protected void paintComponent(Graphics grphcs) {
        Graphics2D g2 = (Graphics2D) grphcs; // Converto o Graphics em Graphics2D pra gráficos avançados
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON); // Ativo o suavizamento das bordas para deixar o desenho mais suave
        GradientPaint g = new GradientPaint(0, 0, Color.decode("#000000"), getWidth(), getHeight(), Color.decode("#737373")); // Gradiente que vai do preto no canto superior esquerdo até um cinza no canto inferior direito
        g2.setPaint(g); //  usar esse gradiente para o desenho
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), 15, 15); //  Preencho um retângulo arredondado que ocupa toda a área do componente com um radius de 15
        super.paintComponent(grphcs); //  Chamando o método da classe pai para garantir que o componente seja desenhado corretamente
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlMy = new javax.swing.JLabel();
        jlDeveloper = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jlMy.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jlMy.setForeground(new java.awt.Color(255, 255, 255));
        jlMy.setText("My");

        jlDeveloper.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jlDeveloper.setForeground(new java.awt.Color(255, 255, 255));
        jlDeveloper.setText("Desenvolvido por Miguel Augusto");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Activities");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jlMy)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jlDeveloper, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jlMy)
                .addGap(0, 0, 0)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(jlDeveloper)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlDeveloper;
    private javax.swing.JLabel jlMy;
    // End of variables declaration//GEN-END:variables
}
